export const SOCKET_CONNECT = 'SOCKET_CONNECT';
export const SOCKET_DISCONNECT = 'SOCKET_DISCONNECT';
export const CHANNEL_CONNECT = 'CHANNEL_CONNECT';
export const CHANNEL_PENDING = 'CHANNEL_PENDING';
export const CHANNEL_DISCONNECT = 'CHANNEL_DISCONNECT';
